FanStrage/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('news/', views.News.as_view(), name='news'),
    path('start/', views.Start.as_view(), name='start'),
    path('recommended/', views.Recommended.as_view(), name='recommended'),
    path('category/', views.Category.as_view(), name='category'),
    path('favorite/', views.Favorite.as_view(), name='favorite'),
    path('inquiry/', views.ContactView.as_view(), name='inquiry'),
    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('members/', views.Members.as_view(), name='members'),
    path('notice/', views.Notice.as_view(), name='notice'),
    path('ranking/', views.Ranking.as_view(), name='ranking'),
    path('information/', views.Information.as_view(), name='information'),
    path('user_create/', views.UserCreate.as_view(), name='user_create'),
    path('user_create/done/', views.UserCreateDone.as_view(), name='user_create_done'),
    path('user_create/complete/<token>/', views.UserCreateComplete.as_view(), name='user_create_complete'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('password_reset/', views.PasswordReset.as_view(), name='password_reset'),
    path('password_reset/done/', views.PasswordResetDone.as_view(), name='password_reset_done'),
    path('password_reset/confirm/<uidb64>/<token>/', views.PasswordResetConfirm.as_view(),
         name='password_reset_confirm'),
    path('password_reset/complete/', views.PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('post_detail/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post_create/', views.PostCreateView.as_view(), name='post_create'),
    path('post_update/<int:pk>/', views.PostUpdateView.as_view(), name='post_update'),
    path('post_delete/<int:pk>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/', views.PostListView.as_view(), name='post'),
]

accounts/forms.py
from django import forms
from .models import Post
from django.contrib.auth.forms import (
    AuthenticationForm, UserCreationForm, PasswordChangeForm,
    PasswordResetForm, SetPasswordForm
)
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.conf import settings

User = get_user_model()


class LoginForm(AuthenticationForm):
    """ログインフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label  # placeholderにフィールドのラベルを入れる


class UserCreateForm(UserCreationForm):
    """ユーザー登録用フォーム"""

    class Meta:
        model = User
        if User.USERNAME_FIELD == 'email':
            fields = ('email',)
        else:
            fields = ('username', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class UserUpdateForm(forms.ModelForm):
    """ユーザー情報更新フォーム"""

    class Meta:
        model = User
        if User.USERNAME_FIELD == 'email':
            fields = ('email', 'first_name', 'last_name')
        else:
            fields = ('username', 'email', 'first_name', 'last_name')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MyPasswordChangeForm(PasswordChangeForm):
    """パスワード変更フォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MyPasswordResetForm(PasswordResetForm):
    """パスワード忘れたときのフォーム"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class MySetPasswordForm(SetPasswordForm):
    """パスワード再設定用フォーム(パスワード忘れて再設定)"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class PostCreateForm(forms.ModelForm):
    """"投稿機能フォーム」"""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    class Meta:
        model = Post
        fields = '__all__'


class ContactForm(forms.Form):
    name = forms.CharField(label='お名前', required=True,
                           widget=forms.TextInput(attrs={'class': 'form-control reset-border-radius', }))
    email = forms.EmailField(label='メールアドレス', required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control reset-border-radius', }))
    message = forms.CharField(label='お問い合わせ内容',
                              widget=forms.Textarea(attrs={'class': 'form-control reset-border-radius', }), required=True)

    # メール送信処理
    def send_email(self):
        # send email using the self.cleaned_data dictionary
        subject = self.cleaned_data['name']
        message = self.cleaned_data['message']
        # email = self.cleaned_data['email']
        from_email = settings.EMAIL_HOST_USER
        to = [settings.EMAIL_HOST_USER]

        send_mail(subject, message, from_email, to)

accounts/views.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView, FormView,
    PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)
from django.contrib.sites.shortcuts import get_current_site
from django.core.signing import BadSignature, SignatureExpired, loads, dumps
from django.http import HttpResponseBadRequest
from django.shortcuts import redirect, resolve_url
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.views import generic

from .models import Post
from .forms import (
    LoginForm, UserCreateForm, UserUpdateForm, MyPasswordChangeForm,
    MyPasswordResetForm, MySetPasswordForm, PostCreateForm, ContactForm,
)

User = get_user_model()


class Index(generic.TemplateView):
    template_name = 'accounts/index.html'


class Login(LoginView):
    """ログインページ"""
    form_class = LoginForm
    template_name = 'accounts/login.html'


class Logout(LoginRequiredMixin, LogoutView):
    """ログアウトページ"""
    template_name = 'accounts/index.html'


class News(generic.TemplateView):
    template_name = 'accounts/news.html'


class Start(generic.TemplateView):
    template_name = 'accounts/start.html'


class Recommended(generic.TemplateView):
    template_name = 'accounts/recommended.html'


class Category(generic.TemplateView):
    template_name = 'accounts/category.html'


class Favorite(generic.TemplateView):
    template_name = 'accounts/favorite.html'


class Information(generic.TemplateView):
    template_name = 'accounts/information.html'


class Inquiry(generic.TemplateView):
    template_name = 'accounts/inquiry.html'


class Members(generic.TemplateView):
    template_name = 'accounts/members.html'


class Notice(generic.TemplateView):
    template_name = 'accounts/notice.html'


class Ranking(generic.TemplateView):
    template_name = 'accounts/ranking.html'


class UserCreate(generic.CreateView):
    """ユーザー仮登録"""
    template_name = 'accounts/user_create.html'
    form_class = UserCreateForm

    def form_valid(self, form):
        """仮登録と本登録用メールの発行."""
        # 仮登録と本登録の切り替えは、is_active属性を使うと簡単。
        # 退会処理も、is_activeをFalseにするだけにしておくと捗ります。
        user = form.save(commit=False)
        user.is_active = False
        user.save()

        # アクティベーションURLの送付
        current_site = get_current_site(self.request)
        domain = current_site.domain
        context = {
            'protocol': 'https' if self.request.is_secure() else 'http',
            'domain': domain,
            'token': dumps(user.pk),
            'user': user,
        }

        subject_template = get_template('accounts/mail_template/create/subject.txt')
        subject = subject_template.render(context)

        message_template = get_template('accounts/mail_template/create/message.txt')
        message = message_template.render(context)

        user.email_user(subject, message)
        return redirect('accounts:user_create_done')


class UserCreateDone(generic.TemplateView):
    """ユーザー仮登録したよ"""
    template_name = 'accounts/user_create_done.html'


class UserCreateComplete(generic.TemplateView):
    """メール内URLアクセス後のユーザー本登録"""
    template_name = 'accounts/user_create_complete.html'
    timeout_seconds = getattr(settings, 'ACTIVATION_TIMEOUT_SECONDS', 60*60*24)  # デフォルトでは1日以内

    def get(self, request, **kwargs):
        """tokenが正しければ本登録."""
        token = kwargs.get('token')
        try:
            user_pk = loads(token, max_age=self.timeout_seconds)

        # 期限切れ
        except SignatureExpired:
            return HttpResponseBadRequest()

        # tokenが間違っている
        except BadSignature:
            return HttpResponseBadRequest()

        # tokenは問題なし
        else:
            try:
                user = User.objects.get(pk=user_pk)
            except User.DoesNotExist:
                return HttpResponseBadRequest()
            else:
                if not user.is_active:
                    # まだ仮登録で、他に問題なければ本登録とする
                    user.is_active = True
                    user.save()
                    return super().get(request, **kwargs)

        return HttpResponseBadRequest()


class OnlyYouMixin(UserPassesTestMixin):
    """本人か、スーパーユーザーだけユーザーページアクセスを許可する"""
    raise_exception = True

    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser


class UserDetail(OnlyYouMixin, generic.DetailView):
    """ユーザー情報詳細画面ビュー"""
    model = User
    template_name = 'accounts/user_detail.html'


class UserUpdate(OnlyYouMixin, generic.UpdateView):
    """ユーザー情報更新ビュー"""
    model = User
    form_class = UserUpdateForm
    template_name = 'accounts/user_form.html'

    def get_success_url(self):
        return resolve_url('accounts:user_detail', pk=self.kwargs['pk'])


class PasswordChange(PasswordChangeView):
    """パスワード変更ビュー"""
    form_class = MyPasswordChangeForm
    success_url = reverse_lazy('accounts:password_change_done')
    template_name = 'accounts/password_change.html'


class PasswordChangeDone(PasswordChangeDoneView):
    """パスワード変更しました"""
    template_name = 'accounts/password_change_done.html'


class PasswordReset(PasswordResetView):
    """パスワード変更用URLの送付ページ"""
    subject_template_name = 'accounts/mail_template/password_reset/subject.txt'
    email_template_name = 'accounts/mail_template/password_reset/message.txt'
    template_name = 'accounts/password_reset_form.html'
    form_class = MyPasswordResetForm
    success_url = reverse_lazy('accounts:password_reset_done')


class PasswordResetDone(PasswordResetDoneView):
    """パスワード変更用URLを送ったよと伝えるページ"""
    template_name = 'accounts/password_reset_done.html'


class PasswordResetConfirm(PasswordResetConfirmView):
    """新パスワード入力ページ"""
    form_class = MySetPasswordForm
    success_url = reverse_lazy('accounts:password_reset_complete')
    template_name = 'accounts/password_reset_confirm.html'


class PasswordResetComplete(PasswordResetCompleteView):
    """新パスワードを設定完了しましたよページ"""
    template_name = 'accounts/password_reset_complete.html'


class PostFilterView(generic.ListView):
    """
    ビュー：フィルターのやつ
    """
    model = Post
    template_name = 'accounts/post.html'

    # 1ページの表示するコンテンツ数
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        """
        表示データの設定
        """
        kwargs['title'] = 'title'
        # 表示データを追加したい場合は、ここでキーを追加しテンプレート上で表示する
        # 例：kwargs['sample'] = 'sample'
        return super().get_context_data(object_list=object_list, **kwargs)


class PostListView(generic.ListView):
    """
    一覧ページ
    """
    model = Post
    template_name = 'accounts/post.html'
    paginate_by = 5


class PostDetailView(generic.DetailView):
    """
    ビュー：詳細画面
    """
    model = Post
    template_name = 'accounts/post_detail.html'

    def get_context_data(self, **kwargs):
        """
        表示データの設定
        """
        # 表示データの追加はここでする予定 例： kwargs['sample'] = 'sample'
        return super().get_context_data(**kwargs)


class PostCreateView(generic.CreateView):
    """
    ビュー：登録画面
    """
    model = Post
    template_name = 'accounts/post_create.html'
    form_class = PostCreateForm
    success_url = reverse_lazy('accounts:post')

    def form_valid(self, form):
        """
        登録処理
        """
        result = super().form_valid(form)
        messages.success(
            self.request, '「{}」を作成しました'.format(form.instance))
        return result


class PostUpdateView(OnlyYouMixin, generic.UpdateView):
    """
    ビュー：更新画面
    """
    model = Post
    form_class = PostCreateForm
    success_url = reverse_lazy('accounts:post')

    def form_valid(self, form):
        """
        更新処理
        """
        result = super().form_valid(form)
        messages.success(
            self.request, '「{}」を更新しました'.format(form.instance))
        return result


class PostDeleteView(OnlyYouMixin, generic.DeleteView):
    """
    ビュー：削除画面
    """
    model = Post
    form_class = PostCreateForm
    success_url = reverse_lazy('accounts:post')

    def delete(self, request, *args, **kwargs):
        """
        削除処理
        """
        result = super().delete(request, *args, **kwargs)
        messages.success(
            self.request, '「{}」を削除しました'.format(self.object))
        return result


class ContactView(FormView):
    """お問い合わせフォーム"""
    template_name = 'accounts/inquiry.html'
    form_class = ContactForm
    success_url = reverse_lazy('accounts:index')

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.send_email()
        return super(ContactView, self).form_valid(form)

accounts/templates/accounts/favorite.html
{% extends 'accounts/base.html' %}

{% block content %}
        <div class="col-lg-1"></div>
        <div class="container col-lg-8">
            <div class="left-container">
                <div class="alert alert-warning" role="alert">
                    <h4 class="alert-heading mb-3">工事中ですm(._.)m</h4>
                    <p>お気に入り機能はまだ実装できておりません。</p>
                    <hr>
                    <div class="container text-center">
                        <a href="{% url 'accounts:start' %}" class="mb-0 btn mx-2">「はじめに」</a>
                        <a href="{% url 'accounts:index' %}" class="mb-0 btn mx-2">「ホーム」</a>
                    </div>
                </div>
            </div>
        </div><!-- /.container -->
{% endblock %}

accounts/templates/accounts/index.html
{% extends 'accounts/base.html' %}
{% load static%}
{% block content %}

        <div class="container col-lg-9">
            <div class="left-container ml-4">
                <div class="container mt-2">
                    <div class="title">
                        <h1>FanStrage</h1>
                        <h2>-A SPORTY LIFE-</h2>
                    </div>
                    <div class="jumbotron home1">
                    </div>
                    <h3>ーTOPICSー</h3>
                    <div class="card-deck mb-3">
                        <div class="card parent">
                            <img src="{% static 'image/#'%}" class="card-img-top" alt="カード3の画像">
                            <div class="card-body">
                                <h3 class="card-title">テキスト</h3>
                                <p class="card-text">テストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテキストテストテストテストテストテストテストテステオテス</p>
                                <p class="card-text underfix"><a href="#!" class="btn read-more">もっとみる</a></p>
                            </div>
                        </div>
                        <div class="card parent">
                            <img src="{% static 'image/#'%}" class="card-img-top" alt="カード3の画像">
                            <div class="card-body">
                                <h3 class="card-title">test</h3>
                                <p class="card-text">テストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテキストテストテストテストテストテストテストテステオテス</p>
                                <p class="card-text underfix"><a href="#!" class="btn read-more">もっとみる</a></p>
                            </div>
                        </div>
                        <div class="card parent">
                            <img src="{% static 'image/#'%}" class="card-img-top" alt="カード3の画像">
                            <div class="card-body">
                                <h3 class="card-title">test</h3>
                                <p class="card-text">テストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテキストテストテストテストテストテストテストテステオテス</p>
                                <p class="card-text underfix"><a href="#!" class="btn read-more">もっとみる</a></p>
                            </div>
                        </div>
                    </div>
                    <div class="card-deck mb-5">
                        <div class="card parent">
                            <img src="{% static '#'%}" class="card-img-top" alt="カード3の画像">
                            <div class="card-body">
                                <h3 class="card-title">test</h3>
                                <p class="card-text">テストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテキストテストテストテストテストテストテストテステオテス</p>
                                <p class="card-text underfix"><a href="#!" class="btn read-more">もっとみる</a></p>
                            </div>
                        </div>
                        <div class="card parent">
                            <img src="{% static 'image/#'%}" class="card-img-top" alt="カード3の画像">
                            <div class="card-body">
                                <h3 class="card-title">tesy</h3>
                                <p class="card-text">テストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテキストテストテストテストテストテストテストテステオテス</p>
                                <p class="card-text underfix"><a href="#!" class="btn read-more">もっとみる</a></p>
                            </div>
                        </div>
                        <div class="card parent">
                            <img src="{% static 'image/#'%}" class="card-img-top" alt="カード3の画像">
                            <div class="card-body">
                                <h3 class="card-title">test</h3>
                                <p class="card-text">テストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテストテキストテストテストテストテストテストテストテステオテス</p>
                                <p class="card-text underfix"><a href="#!" class="btn read-more">もっとみる</a></p>
                            </div>
                        </div>
                    </div>
                    <div class="bd-example col-lg-7 moving mb-5">
                        <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
                                <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
                                <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner" role="listbox">
                                <div class="carousel-item active">
                                    <img src="{% static 'image/#'%}" class="d-block w-100" data-src="holder.js/900x300?auto=yes&amp;bg=777&amp;fg=555&amp;text=First slide"
                                        alt="First slide [900x300]" data-holder-rendered="true">
                                    <div class="carousel-caption d-none d-md-block">
                                        <div class="textlist">
                                            <h3>おすすめ</h3><p>tesy</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="carousel-item">
                                    <img src="{% static 'image/#'%}" class="d-block w-100" data-src="holder.js/900x300?auto=yes&amp;bg=666&amp;fg=444&amp;text=Second slide"
                                        alt="Second slide [900x300]" data-holder-rendered="true">
                                    <div class="carousel-caption d-none d-md-block">
                                        <div class="textlist">
                                            <h3>ランキング：1位</h3><p>team1</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="carousel-item">
                                    <img src="{% static 'image/#'%}" class="d-block w-100" data-src="holder.js/900x300?auto=yes&amp;bg=666&amp;fg=444&amp;text=Second slide"
                                        alt="Second slide [900x300]" data-holder-rendered="true">
                                    <div class="carousel-caption d-none d-md-block">
                                        <div class="textlist">
                                            <h3>test</h3><p>test</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    </div>
                    <div class="col-lg-5 sections mb-5">
                        <div class="topics">
                            <h1>おすすめ</h1>
                            <h2>test</h2>
                        </div>
                        <div class="topics">
                            <h1>ランキング</h1>
                            <ul class="rank">
                                <li>
                                    <p>１位：</p><h2>tesy</h2>
                                </li>
                                <li>
                                    <p>２位：</p><h2>test</h2>
                                </li>
                                <li>
                                    <p>３位；</p><h2>test</h2>
                                </li>
                            </ul>
                        </div>
                        <div class="topics">
                            <h1>本日の献立</h1>
                            <h2>test</h2>
                        </div>
                    </div>
                </div><!-- /.container -->
            </div>
        </div><!-- /.container -->
{% endblock %}

accounts/templates/accounts/password_change_done.html
{% extends "accounts/base.html" %}
{% block content %}
<div class="col-lg-1"></div>
        <div class="container col-lg-8">
            <div class="left-container mt-5">
                <div class="alert alert-info my-4" role="alert">
                    <h4 class="alert-heading mb-3 pt-4 text-center">パスワードを変更しました。</h4>
                    <p><a class="btn mt-4" href="{% url 'accounts:login' %}">ログイン</a></p>
                </div>
            </div>
        </div>
{% endblock %}

accounts/templates/accounts/post.html
{% extends 'accounts/base.html' %}

{% block content %}
        <div class="col-lg-1"></div>
        <div class="container col-lg-8">
            <div class="left-container mt-5">
                <h2><span><i class="far fa-edit fa-fw"></i></span>投稿一覧<span><i class="far fa-edit fa-fw"></i></span></h2>
                <div class="row">
                    <div class="col-12 card-deck mt-3">

                        {% for item in object_list %}
                        <div class="card parent">
                            <div class="card-body">
                                <h3 class="card-title">{{ item }}</h3>
                                <p class="card-text">{{ item.subtitle }}</p>
                                <p class="card-text underfix"><small class="text-muted mr-2">{{ item.created_at }}</small><a class="btn" href="{% url 'accounts:post_detail' item.pk %}">もっと見る</a></p>
                            </div>
                        </div>
                        {% empty %}
                            <li class="list-group-item">
                                対象のデータがありません
                            </li>
                        {% endfor %}

                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-12">
                        <div class="text-center mt-2 mb-3">
                            <a class="btn" href="{% url 'accounts:post_create' %}">投稿する</a>
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- /.container -->

{% endblock %}

<!--<div class="col-12">-->
    <!--<div class="mt-3 text-center">-->
      <!--{% if page_obj.has_previous %}-->
        <!--<a class="btn btn-secondary" href="/?page={{ page_obj.previous_page_number }}">前へ</a>-->
      <!--{% endif %}-->
      <!--<span>{{ page_obj.number }}/{{ paginator.num_pages }}ページ</span>-->
      <!--{% if page_obj.has_next %}-->
        <!--<a class="btn btn-secondary" href="/?page={{ page_obj.next_page_number }}">次へ</a>-->
      <!--{% endif %}-->
    <!--</div>-->
<!--</div>-->

accounts/templates/accounts/post_confirm_delete.html
{% extends 'accounts/base.html' %}

{% block content %}
<div class="col-lg-1"></div>
<div class="container col-lg-8">
    <h2 class="text-center">データ削除</h2>
    <form action="" method="post">
        {% csrf_token %}
        <div class="card card-default">
            <div class="card-body">
              {% include "./post_detail_contents.html" %}
            </div>
            <div class="card-footer text-center">
                <p>このデータを削除します。よろしいですか？</p>
                <p>{{ object }} を削除していいですか?</p>
                <a class="btn" href="{% url 'accounts:post' %}">戻る</a>
                <input type="submit" class="btn delete" value="削除">
            </div>
        </div>
    </form>
</div>
{% endblock %}

accounts/templates/accounts/post_detail.html
{% extends 'accounts/base.html' %}
{% block content %}
    <div class="col-lg-1"></div>
    <div class="container col-lg-8 mt-5">
        <h2 class="text-center mb-4">投稿詳細</h2>
        <div class="card card-default">
            <div class="card-body">
              {% include "./post_detail_contents.html" %}
            </div>
            <div class="card-footer text-center">
                <a class="btn btn-primary" href="{% url 'accounts:post_update' object.pk %}">修正</a>
                <a class="btn btn-danger" href="{% url 'accounts:post_delete' object.pk %}">削除</a>
                <a class="btn" href="{% url 'accounts:post' %}">戻る</a>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/ranking.html
{% extends 'accounts/base.html' %}

{% block content %}
        <div class="col-lg-1"></div>
        <div class="container col-lg-8">
            <div class="left-container">
                <div class="alert alert-warning" role="alert">
                    <h4 class="alert-heading mb-3">工事中ですm(._.)m</h4>
                    <p>ランキングができるほど、掲載されていません。</p>
                    <hr>
                    <div class="container text-center">
                        <a href="{% url 'accounts:start' %}" class="mb-0 btn mx-2">「はじめに」</a>
                        <a href="{% url 'accounts:index' %}" class="mb-0 btn mx-2">「ホーム」</a>
                    </div>
                </div>
            </div>
        </div><!-- /.container -->
{% endblock %}

accounts/templates/accounts/recipe.html
{% extends 'accounts/base.html' %}

{% block content %}
        <div class="col-lg-1"></div>
        <div class="container col-lg-8">
            <div class="left-container mt-5">
                <h2><span><i class="far fa-edit fa-fw"></i></span>投稿一覧<span><i class="far fa-edit fa-fw"></i></span></h2>
                <div class="row">
                    <div class="col-12 card-deck mt-3">

                        {% for item in object_list %}
                        <div class="card parent">
                            <div class="card-body">
                                <h3 class="card-title">{{ item }}</h3>
                                <p class="card-text">{{ item.subtitle }}</p>
                                <p class="card-text underfix"><small class="text-muted mr-2">{{ item.created_at }}</small><a class="btn" href="{% url 'accounts:recipe_detail' item.pk %}">もっと見る</a></p>
                            </div>
                        </div>
                        {% empty %}
                            <li class="list-group-item">
                                対象のデータがありません
                            </li>
                        {% endfor %}

                    </div>
                </div>
                <div class="row mt-5">
                    <div class="col-12">
                        <div class="text-center mt-2 mb-3">
                            <a class="btn" href="{% url 'accounts:recipe_create' %}">投稿する</a>
                        </div>
                    </div>
                </div>
            </div>
        </div><!-- /.container -->

{% endblock %}

<!--<div class="col-12">-->
    <!--<div class="mt-3 text-center">-->
      <!--{% if page_obj.has_previous %}-->
        <!--<a class="btn btn-secondary" href="/?page={{ page_obj.previous_page_number }}">前へ</a>-->
      <!--{% endif %}-->
      <!--<span>{{ page_obj.number }}/{{ paginator.num_pages }}ページ</span>-->
      <!--{% if page_obj.has_next %}-->
        <!--<a class="btn btn-secondary" href="/?page={{ page_obj.next_page_number }}">次へ</a>-->
      <!--{% endif %}-->
    <!--</div>-->
<!--</div>-->